#! /bin/bash

trash=$HOME/trash
date=`date '+%Y%m%d%H%M%S'`
option=()

if [ ! -d $trash ]
then
    mkdir -p $trash
fi

for i
do
    case $i in
        --interactive|--force|--verbose)
            option+=("$i")
            ;;
        --*) ;;
        -*)
            opt=`echo $i | sed -e s/[^-fiv]//g`
            option+=("$opt")
            ;;
        *) ;;
    esac
done

for i
do
    case $i in
        -*) ;;
        *)
            if [ -e $i ]
            then
                mv ${option[@]} $i $trash/$date_`basename $i`
            fi
            ;;
    esac
done
