#! /bin/sh
trash=$HOME/trash
date=`date '+%Y%m%d%H%M%S'`

if [ ! -d $trash ]
then
    mkdir -p $trash
fi

for i
do
    case $i in
        -*) ;;
        *) mv $i $trash/`basename $i`.$date ;;
    esac
done
